listo antes evaluación

diff --git a/bash/script03/scdebug b/bash/script03/scdebug
--- a/bash/script03/scdebug
+++ b/bash/script03/scdebug
@@ -12,10 +12,12 @@ TRACEE_PID=""
 KILL_TRACES=""
 ATTACH_PROGRAM=""
 PATTCH_PID=""
+STRACE_ERROR=""
+LISTA_PROCESOS=""
 
 # Funciones
 usage() {
-  echo "scdebug [-h] [-sto arg] [-v | -vall] [-k] [prog [arg …] ] [-nattch progtoattach …] [-pattch pid1 … ]
+  echo "scdebug [-h] [-sto arg] [-k] [prog [arg …] ] [-nattch progtoattach …] [-pattch pid1 … ]
 --help o -h para más información"
 }
 
@@ -35,7 +37,6 @@ arg_check() {
         ;;
       -k)
         KILL_TRACES="1"
-        shift
         kill_traces 2> /dev/null
         exit 0
         ;;
@@ -48,7 +49,7 @@ arg_check() {
         exit 0
         ;;
       -* )
-        if [ "$STRACE_ARGS" = "1" ]; then
+        if [ "$STRACE_ARGS" = "1" ] && [ -z $PROGRAM ]; then
           STRACE_ARG_LIST+="$1 "
         else 
           if [ -n "$PROGRAM" ]; then
@@ -63,11 +64,11 @@ arg_check() {
       * )
         if [ -n "$PATTCH" ]; then
           PATTCH_PID="$1"
-          pattch_option
+          pattch_option& 2> /dev/null
         fi
         if [ -n "$ATTACH" ]; then
           ATTACH_PROGRAM="$1"
-          nattch_option
+          nattch_option& 2> /dev/null
         fi
         if [ -n "$PROGRAM" ]; then
           PROGRAM_ARGS+=" $1"
@@ -94,11 +95,6 @@ help() {
   -pattch [PID ...]: se hace strace con attach a cada uno de los PID pasados por argumento"
 }
 
-tracer_and_tracee_pid() {
-  TRACEE_PID=$(pgrep -n "$PROGRAM")
-  TRACER_PID=$(cat 2> /dev/null /proc/$TRACEE_PID/status | grep "TracerPid" | cut -f 2)
-}
-
 kill_traces() {
   for i in $(ps -u $USER --no-header | sort -r | tr -s " " | cut -d " " -f 2); do
     if [ "$(cat /proc/$i/status | grep "TracerPid" | cut -f 2)" != "0" ]; then
@@ -117,12 +113,12 @@ nattch_option () {
   echo "Programa a monitorizar: $ATTACH_PROGRAM"
   OUTPUT_FILE="$HOME/.scdebug/$ATTACH_PROGRAM/trace_$TRACE_ID.txt"
   OUTPUT_DIR="$HOME/.scdebug/$ATTACH_PROGRAM"
-  mkdir -p $OUTPUT_DIR && (strace 2> /dev/null $STRACE_ARG_LIST -p $PID -o $OUTPUT_FILE& 2> /dev/null)
-  ps -u $USER | tr -s " " | cut -d " " -f 2,5 2> /dev/null  
-  TRACER_PID=$(cat /proc/$PID/status | grep "TracerPid" | cut -f 2)
-  echo "PID del tracer: $TRACER_PID"
-  echo "PID del tracee: $PID"
-  echo
+  mkdir 2> /dev/null -p $OUTPUT_DIR 
+  (strace 2>&1 $STRACE_ARG_LIST -p $PID -o $OUTPUT_FILE) || STRACE_ERROR="$?"
+  if [ -n "$STRACE_ERROR" ]; then
+    echo "No se pudo monitorizar el programa $ATTACH_PROGRAM, strace falló con el error $STRACE_ERROR" | tee -a $OUTPUT_FILE
+    exit 4
+  fi
 }
 
 pattch_option() {
@@ -134,31 +130,56 @@ pattch_option() {
   echo "Programa a monitorizar: $PATTCH_PROGRAM"
   OUTPUT_FILE="$HOME/.scdebug/$PATTCH_PROGRAM/trace_$TRACE_ID.txt"
   OUTPUT_DIR="$HOME/.scdebug/$PATTCH_PROGRAM"
-  mkdir -p $OUTPUT_DIR && (strace 2> /dev/null $STRACE_ARG_LIST -p $PATTCH_PID -o $OUTPUT_FILE& 2> /dev/null)
-  ps -u $USER | tr -s " " | cut -d " " -f 2,5 2> /dev/null
-  TRACER_PID=$(cat /proc/$PATTCH_PID/status | grep "TracerPid" | cut -f 2)
-  echo "PID del tracer: $TRACER_PID"
-  echo "PID del tracee: $PATTCH_PID"
-  echo
+  mkdir 2>/dev/null -p $OUTPUT_DIR 
+  (strace 2> /dev/null $STRACE_ARG_LIST -p $PATTCH_PID -o $OUTPUT_FILE) || STRACE_ERROR="$?"
+  if [ -n "$STRACE_ERROR" ]; then
+    echo "No se pudo monitorizar el programa con el PID $PATTCH_PID, strace falló con el error $STRACE_ERROR" | tee -a $OUTPUT_FILE
+    exit 4
+  fi
 }
 
 normal_strace() {
   OUTPUT_FILE="$HOME/.scdebug/$PROGRAM/trace_$TRACE_ID.txt"
   OUTPUT_DIR="$HOME/.scdebug/$PROGRAM"
-  mkdir -p $OUTPUT_DIR && (strace 2> /dev/null $STRACE_ARG_LIST -o $OUTPUT_FILE $PROGRAM $PROGRAM_ARGS)
-  tracer_and_tracee_pid
-  echo "PID del tracer: $$"
-  echo "PID del tracee: $TRACEE_PID"
-  echo
-  ps -u $USER 2> /dev/null | tr -s " " | cut -d " " -f 2,5
+  mkdir 2> /dev/null -p $OUTPUT_DIR 
+  strace 2>&1 $STRACE_ARG_LIST -o $OUTPUT_FILE $PROGRAM $PROGRAM_ARGS || STRACE_ERROR="$?"
+  if [ -n "$STRACE_ERROR" ]; then
+    echo "No se pudo monitorizar el programa $PROGRAM, strace falló con el error $STRACE_ERROR" | tee -a $OUTPUT_FILE
+    exit 4
+  fi
   exit 0
+}
+
+tracer_and_tracee_pid() {
+  LISTA_PROCESOS="$(ps -u $USER --no-header | sort -r | tr -s " " | cut -d " " -f 2)"
+  for i in $LISTA_PROCESOS; do
+    echo "NOMBRE: $(ps 2>/dev/null -p $i --no-header | tr -s " " | cut -d " " -f 5)"
+    echo "PID: $i"
+    TRACER_PID=$(cat 2>/dev/null /proc/$i/status | grep "TracerPid" | cut -f 2)
+    echo "TracerPid: $TRACER_PID"
+    echo "TracerID: $(ps 2>/dev/null -p $TRACER_PID --no-header | tr -s " " | cut -d " " -f 5)"
+    echo
+  done
 }
 
 # Programa principal
 arg_check "$@"
 
 if [ -n "$ATTACH" ] || [ -n "$PATTCH" ]; then
+  sleep 0.1
+  if [ -z "$STRACE_ERROR" ]; then
+    tracer_and_tracee_pid
+  fi
   exit 0
 else
-  normal_strace& 2> /dev/null
+  if [ -z "$PROGRAM" ]; then
+    echo "No se ha introducido ningún programa"
+    usage
+    exit 3
+  fi
+  normal_strace&
 fi
+
+sleep 0.1
+
+tracer_and_tracee_pid
